---
title: "Distribution_Statistics"
author: "Tim Monko"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, include = FALSE}
library(tidyverse) # Includes ggplot2, tidyr, dply*r, stringr, readr, tibble, purrr, forcats
library(svglite) # For exporting plots as .svg graphics to use as vector format
library(broom) # Tidy's up some statistical outputs
library(extrafont) # README: https://cran.r-project.org/web/packages/extrafont/README.html   // 
#font_import(path = 'C:/Users/TimMonko/AppData/Local/Microsoft/Windows/Fonts') # for custom installed .ttf fonts
library(unicycles)
extrafont::loadfonts(device = "win", quiet = TRUE) 
Sys.setenv(R_GSCMD="C:/Program Files/gs/gs9.52/bin/gswin64c.exe") # Set the location for Ghostscript for pdf embedding of fonts, use embed_fonts()

`%notin%` = Negate(`%in%`) # Used to define a group by what is NOT in the group
```

```{r cache_settings, echo = FALSE}
# Create a directory so as to 
dir.name <- 'S1V1_new_RORBrn2EdU_Stats'
dir.create(dir.name)

knitr::opts_chunk$set(cache = TRUE, cache.path = paste0(dir.name, '-cache/')) # fig.path = 'Figs/' ## Will save figs into a separate file 
```

```{r data_management, echo = FALSE}
# echo = FALSE prevents printing of mundance code (can always set a function clause to echo = TRUE, if needed), by default echo = TRUE

wd.path <- getwd()
file.paths <- list.files(path = wd.path, pattern = '\\.csv$')

# Use all cols to identify certain columns as factors, without this it cannot generate the correct tibble, instead just forcing them into whatever it considers 'ideal'
all.cols <- cols(
  genotype = col_factor(),
  slice = col_factor(),
  pair = col_factor(),
  region = col_factor()
)

# A function for csv bind - brings in each file to create one master tibble 
csv_bind <- function(wd.path = getwd(), text.pattern, col.types){
  bound <- do.call(rbind,
                    lapply(list.files(path = wd.path, pattern = text.pattern),
                           function(x) read_csv(x, col_types = col.types)))
  return(bound)
}

# Use the function to call in files from getwd() [the default] based on the pattern within the file name
all.centers <- csv_bind(text.pattern = 'centers', col.types = all.cols)

# Likely the most useful datasets, the origin of the original analysis of investigating cell mean pooled across sections. *
summarize.cells<- csv_bind(text.pattern = 'cellmean', col.types = all.cols)

# This uses both relative bin and absolute bin distances as determined from the previously run R_Image_Analysis file, no helper .csv is yet available to show bin sizes and such 
summarize.bins<- csv_bind(text.pattern = 'bins', col.types = all.cols)

```

```{r ratiometric_statistics, echo = FALSE}

# Change data to just cell counts in wide format, for ratiometric calculations
summarized.wide <- summarize.cells %>% 
  # filter(region == 'S1') %>% # should probably not filter by region here, because this will prevent good data management later - only remove when necessary 
  pivot_wider(id_cols = c(genotype, pair, region), names_from = slice, values_from = cells, names_prefix = 'cells_') # %>% replace(is.na(.),0) # NAs in the dataset become zero

# Divide columns to produce ratiometric data of X+ cell over Y+ cell or X+Y+ cell over Z cell, etc. 
summarized.manip <- summarized.wide %>%
  mutate(ROR_EdU = cells_5/cells_3) %>% # Brn2+EdU+/EdU+ cells (how many of the EdU cells are Brn2 labeled)
  mutate(Brn2_EdU = cells_6/cells_3) %>%
  mutate(ROREdU_Brn2EdU = cells_7/cells_8) %>%
  mutate(ROR_Brn2 = cells_1/cells_2)

# Grab column names to be used after the function call to a numeric column, could also be used as a vector of strings, but that seems like way too much work
summarized.col.names <- colnames(summarized.manip)

# Remove pairs using a numeric vector like c(). If logical then skipped to remove pairs 
rmpairs = NA

if (is.logical(rmpairs)) {
  rmpair.summarized <- summarized.manip
  } else {
  rmpair.summarized <- filter(summarized.manip, pair %notin% c(rmpairs))
}

filt.region = 'S1'
rmpair.summarized.region <- rmpair.summarized %>%
  filter(region == filt.region)

# Function created to run a two-way ttest (cell column x genotype) with the, by default, cell mean dataset
#     ***For using a column name as an argument, use the [[column_name]] and then in the function call it as a string
#     ***New method of using functions give's same statistical results as the old one, however a question yet tbd is why does the two-way PAIRED t-test give different answer than one-way/relative paired ttest - is it because Welch's is the default? 
fn_ttest_paired <- function(col, df = rmpair.summarized.region) {
  col2 <- summarized.col.names[col]
  z <- t.test(df[[col2]] ~ genotype,  df, paired = TRUE)
  z$data.name <- col2
  return(z)
}

# !!!! This may work better as a one-way ANOVA, allowing to compare multiple groups (V1/S1 x Genotype)

# Create an empty list for storing function output (lists are considered best function -> storage practice)
paired.list = list()

# Use for loop to iterate on all sequential columns desired. By default data starts in column 4
for (i in 4:15) {
  b <- fn_ttest_paired(i) # Store result (z) from function to b
  b <- tidy(b) # Create a 1 line tibble of b, from the default ttest output
  b <- add_column(b, col = summarized.col.names[i], .before = 1) # add a column with the cell title to the left of the tibble
  paired.list[[i]] <- b # Move tibble to a list 
}
paired.results <- bind_rows(paired.list) # bind the list-stored tibbles to a dataframe 
paired.results
```

```{r rel_statistics}
# Filter out genotypes for comparisons 
WT.summarized <- summarized.manip %>%
  filter(genotype == 'WT') %>%
  group_by(genotype, pair)
CKO.summarized <- summarized.manip %>%
  filter(genotype == 'CKO') %>%
  group_by(genotype, pair)

# Divide CKO by WT to produce the relative ratio of cell numbers of CKO to WT, then add a row for all the pairs (at the end )
rel.CKO.summarized <- CKO.summarized[-1:-3]/WT.summarized[-1:-3] 

# adds back in the 
rel.CKO.summarized <- rel.CKO.summarized %>%
  add_column(region = CKO.summarized$region, pair = CKO.summarized$pair, genotype = CKO.summarized$genotype)

# Pull out column names for function calls on column number
rel.col.names <- colnames(rel.CKO.summarized)

# Remove pairs using a numeric vector like c(). If logical then skipped to remove pairs 
rmpairs = NA

filt.region = 'S1'
rel.CKO.summarized.rg <- rel.CKO.summarized %>%
  filter(region == filt.region)

if (is.logical(rmpairs)) {
  rel.oneway <- rel.CKO.summarized.rg
  } else {
  rel.oneway <- filter(rel.CKO.summarized.rg, pair %notin% c(rmpairs))
}



# Function created to run a one-way ttest (relative mean x mu =1 (WT ratio)) 
# Uses the dplyr select call to bring the column name into the t.test, could probably work as in the above two way ttest 
fn_ttest_oneway <- function(col, df = rel.oneway) {
  z <- t.test(select(df, rel.col.names[col]), mu =1)
  z$data.name <- rel.col.names[col]
  return(z)
}

# See two-way ttest for destricption of the list/forloop
oneway.list = list()
for (i in 1:13) {
  b <- fn_ttest_oneway(i)
  b <- tidy(b)
  b <- add_column(b, col = rel.col.names[i], .before = 1)
  oneway.list[[i]] <- b
}
oneway.results <- bind_rows(oneway.list)
oneway.results

```

```{r plotting_means_new}
# Custom Gray Palette by Tim (no yellow) and slightly reorganized. Originally from: http://jfly.iam.u-tokyo.ac.jp/color/  and http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbpTim <- c('#999999', '#E69F00', '#56B4E9', '#009E73', '#D55E00', '#0072B2', '#CC79A7')
# To use for fills, add
#   scale_fill_manual(values=cbTim)
# To use for line and point colors, add
#   scale_colour_manual(values=cbTim)

rmpairs.plot = NA # To remove pairs use vector, otherwise use non-numeric
columns.plot = c(3,7,8) # Which columns should be plotted, can call by order 

if (is.logical(rmpairs.plot)) {
  rel.CKO.plot <- rel.CKO.summarized
  } else {
  rel.CKO.plot <- filter(rel.CKO.summarized, pair %notin% c(rmpairs))
}


# !!! This is problematic for multi-level cases hmmm <- see before keeping CKO data across the summarization. 
rel.summarized.plot <- rel.CKO.plot %>%   # to subtract any desired rows   mutate(pair = 1:10) %>%
  pivot_longer(cols = c(3,7,8), names_to = 'cells', values_to = 'rel.mean')

rel.avgmeans.plot <- rel.summarized.plot %>%
  group_by(region, cells) %>%
  summarize(avg.rel = mean(rel.mean, na.rm = TRUE), sd.rel = sd(rel.mean)) %>%
  ungroup()

plot.relative.means <- ggplot(rel.summarized.plot, aes(x = 0, y = rel.mean, colour = cells)) +
  facet_wrap(~ region, strip.position = 'bottom', nrow = 1) +
  theme_classic(base_size = 7) +
  geom_jitter(size = 1, shape = 1, position = position_jitterdodge(jitter.width = 0.5, dodge.width = 5)) +
  geom_point(data = rel.avgmeans.plot, size = 5, shape = 13, stroke = 0.6, aes(y = avg.rel), position = position_dodge(5)) + 
  geom_hline(aes(yintercept = 1), linetype = 'dashed') +
  scale_colour_manual(values = cbpTim, name = NULL, labels = c('EdU', 'ROR+EdU+', 'BRN2+EdU+', 'ROR+EdU+', 'BRN2+EdU+')) +
  labs(y = 'Rel. Cell#, CKO/WT',
       x = NULL) + # can use element_blank for no label at all
  #ylim(NA, NA) +
  scale_x_discrete() +
  guides(color = guide_legend(override.aes = list(size = 3),   
                              label.position = 'left',
                              label.hjust = 1))  #size = 3 reduces the key icon for the colour header to a smaller size 

plot.relative.means + theme_Tim() # theme_Tim was adapted from the Ib packaged and installed now using Tim Monko's custom package 'unicycles'
```

```{r savings_plots1}
# Specifically for saving plots so that it's unnecessary to worry about 
plot.relative.means + theme_Tim() # theme_Tim was adapted from the Ib packaged and installed now using Tim Monko's custom package 'unicycles'


ggsave(filename = paste0('EdUDoubles_FinalD.png'), device = 'png', width = 6*1.32, height = 3*1.32, unit = 'cm', dpi = 1000)
ggsave(filename = paste0('EdUDoubles_FinalD.svg'), device = 'svg', width = 6*1.32, height = 3*1.32, unit = 'cm')
```

```{r plotting_ratio stuff }

# Custom Gray Palette by Tim (no yellow) and slightly reorganized. Originally from: http://jfly.iam.u-tokyo.ac.jp/color/  and http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbTim <- c('#999999', '#E69F00', '#56B4E9', '#009E73', '#D55E00', '#0072B2', '#CC79A7')
cbGenotype <- c('#d95f02', '#7570b3')
# To use for fills, add
#   scale_fill_manual(values=cbTim)
# To use for line and point colors, add
#   scale_colour_manual(values=cbTim)

plot.wide <- summarized.manip  # Maintains the initial mathematically calculated 

rmpairs.plot = c(4) # To remove pairs use a numeric vector vector, otherwise use a non-numeric
pivot.columns <- c(15)

if (is.logical(rmpairs.plot)) {
  ratio.plot.wide <- plot.wide
  } else {
  ratio.plot.wide <- filter(plot.wide, pair %notin% c(rmpairs))
}

# !!! This is problematic for multi-level cases hmmm <- see before keeping CKO data across the summarization. 
ratio.summarized.plot <- ratio.plot.wide %>%
  mutate(Genotype = factor(genotype, levels=c("WT", "CKO"))) %>%
  pivot_longer(cols = c(`Brn2_EdU`, `ROR_EdU`), names_to = 'cells', values_to = 'ratio') ##!! Fix faceting of cols

ratio.avgmeans.plot <- ratio.summarized.plot %>%
  group_by(region, cells, Genotype) %>%
  summarize(avg.ratio = mean(ratio, na.rm = TRUE), sd.ratio = sd(ratio)) %>%
  ungroup()
  
# Cells lab is useful to give names to factors, so first store the strings and then use names() to label the respect level
cells.lab <- c('ROR+EdU+/EdU+', 'Brn2+EdU+/EdU+', 'ROR+EdU+/Brn2+EdU+')
names(cells.lab) <- c('ROR_EdU', 'Brn2_EdU', 'ROREdU_Brn2EdU') 


ratio.plot <- ggplot(ratio.summarized.plot, aes(x = 0, y = ratio, shape = Genotype, colour = Genotype)) +
  facet_wrap( ~ region + cells,  strip.position = 'bottom', nrow = 1, labeller = labeller(cells = cells.lab)) +
    theme_classic(base_size = 7) +
  geom_jitter(size = 1, shape = 1, position = position_jitterdodge(jitter.width = 0.5, dodge.width = 5)) +
  geom_point(data = ratio.avgmeans.plot, size = 5,  stroke = 0.6, aes(y = avg.ratio), position = position_dodge(5)) + 
  #scale_colour_manual(values = cbp1, name = NULL, labels = c('ROR+EdU+/EdU+', 'Brn2+EdU+/EdU+', 'ROR+EdU+/ROR+', 'Brn2+EdU+/Brn2', 'BRN2+EdU+')) +
  labs(y = 'ROR+EdU+/Brn2+EdU+',
       x = element_blank()) +
  #ylim(NA, 1.3) +
  scale_x_discrete(labels = c('WT', 'cKO')) +
  scale_shape_manual(values = c(7, 10)) +
  scale_colour_manual(values = cbGenotype) +
  guides(shape = guide_legend(override.aes = list(size = 3),   
                              label.position = 'left',
                              label.hjust = 1))  #size = 3 reduces the key icon for the colour header to a smaller size 

ratio.plot + theme_Tim()
```

```{r saving_plots2}

ratio.plot + theme_Tim()


ggsave(filename = paste0('ROREdUBrn2EdU-FinalD.png'), device = 'png', width = 4*1.32, height = 4*1.32, unit = 'cm', dpi = 1000)
ggsave(filename = paste0('Allratio-FinalD.svg'), device = 'svg', width = 8*1.32, height = 4*1.32, unit = 'cm')

```
